### ISSUE TITLE
Is there a documentation available for the source code?

### ISSUE THREAD

**Issue by harishydav** [Altruisto/altruisto#6]
I wish to build clone of altruisto for raising money in India through affliate commissions. 

If you wish to help me out with the specifics, I would love to collaborate.

**Comment by dwyrzykowski** [comment]
Hey, I am currently working on a new version, so the code base will change pretty dramatically in the upcoming weeks. You can watch for the changes on the branch `feat/panel-account-notifications`.

That being said, even though current code is sometimes a bit "smelly" (like redundant ifs etc.) it's pretty self-explanatory plus it has quite a bit of comments, so that should be good enough to get you started.

**Comment by kovsky0** [comment]
Hey, I am currently working on a new version, so the code base will change pretty dramatically in the upcoming weeks. You can watch for the changes on the branch feat/panel-account-notifications.

That being said, even though current code is sometimes a bit "smelly" (like redundant ifs etc.) it's pretty self-explanatory plus it has quite a bit of comments, so that should be good enough to get you started.
